services:
  oloy.audit.log.command_handler:
    class: OpenLoyalty\Component\Audit\Domain\Command\AuditLogHandler
    arguments:
      - '@oloy.audit.log.repository'
      - '@broadway.uuid.generator'
      - '@broadway.event_dispatcher'
    lazy: true
    tags:
      - { name: command_handler }
  oloy.audit.log.repository:
    class: OpenLoyalty\Component\Audit\Infrastructure\Persistence\Doctrine\Repository\DoctrineAuditLogRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Component\Audit\Domain\AuditLog'
